version: '3.3'

services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia

    ports:
      - 9091:9091

    volumes:
      - <path/to/host/config>:/config
    environment:
      - TZ=Europe/Brussels
