version: '2.1'

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr

    restart: unless-stopped

    ports:
      - 9696:9696

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - </path/to/host/config>:/config
