# mkdir /root/Docker/uptimekuma

version: '3'

services:
  uptimekuma:
    image: louislam/uptime-kuma:latest
    container_name: uptimekuma

    restart: always

    ports:
      - 3001:3001

    volumes:
      - /root/Docker/uptimekuma/app:/app/data