version: '3'

services:
  collabora:
    image: collabora/code
    container_name: collabora

    restart: unless-stopped
    cap_add:
      - MKNOD
    tty: true

    ports:
      - 9980:9980
    expose:
      - "9980"

    environment:
      - domain=<wildcard.domain.example nextcloud>
      - 'dictionaries=en_US,nl_BE'
      - VIRTUAL_PROTO=http
      - VIRTUAL_PORT=9980
      - VIRTUAL_HOST=<wildcard.domain.example of collabora>
      - "extra_params=--o:ssl.enable=false  --o:ssl.termination=true"
