version: '3'

services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud

    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

    ports:
      - 8080:80

    volumes:
      - </path/to/host/config>:/config
      - </path/to/host/data>:/data
      - </>:/mnt/<name>
    environment:
      - PUID=<$ id -u>
      - PGID=<$ id -g>
      - TZ=Europe/Brussels

  collabora:
    image: collabora/code
    container_name: collabora

    restart: unless-stopped
    cap_add:
      - MKNOD
    tty: true

    ports:
      - 9980:9980
    expose:
      - "9980"

    environment:
      - domain=<wildcard.domain.example nextcloud>
      - 'dictionaries=en_US,nl_BE'
      - VIRTUAL_PROTO=http
      - VIRTUAL_PORT=9980
      - VIRTUAL_HOST=<wildcard.domain.example of collabora>
      - "extra_params=--o:ssl.enable=false  --o:ssl.termination=true"
