version: '3'

services:
  rtmp:
    image: tiangolo/nginx-rtmp:latest
    container_name: rtmp

    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

    ports:
      - 1935:1935
