# A simple, yet powerful dashboard for your server
# mkdir /root/Docker/homarr

version: '3'

services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped

    ports:
      - 7575:7575

    volumes:
      - /root/Docker/homarr:/app/data/configs
      - /root/Docker/homarr:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro
