version: '3'

services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped

    ports:
      - 7575:7575

    volumes:
      - </path/to/host/configs>:/app/data/configs
      - </path/to/host/icons>:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro
