version: '2.1'

services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr

    restart: unless-stopped

    ports:
      - 6767:6767

    volumes:
      - </path/to/host/config>:/config
      - </path/to/host/movies>:/movies
      - </path/to/host/tv>:/tv
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
