version: '2.1'

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent

    restart: unless-stopped

    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp

    volumes:
      - </path/to/host/config>:/config
      - </path/to/host/Downloads>:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - WEBUI_PORT=8080
