version: '2.1'

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr

    restart: unless-stopped

    ports:
      - 8989:8989

    volumes:
      - </path/to/host/config>:/config
      - </path/to/host/tv>:/tv
      - </path/to/host/Downloads>:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
