version: '3'

services:
  guacamole:
    image: maxwaldorf/guacamole
    container_name: guacamole

    restart: unless-stopped

    ports:
      - 8080:8080

    volumes:
      - </path/to/host/config>:/config

networks:
  proxy:
    external: true
