# mkdir /root/Docker/heimdall
# set Volumes to /root/Docker/heimdall:

version: '3'
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall_website
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - /root/Docker/heimdall/config:/config
    ports:
      - 81:81
      - 444:444
    restart: unless-stopped