version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    restart: always
    ports:
      - 3000:3000
    volumes:
      - </path/to/host/config>:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
