version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden

    restart: always

    ports:
      - 80:80

    volumes:
      - <path/to/host/data>:/data
    environment:
      - SMTP_HOST=smtp.gmail.com
      - SMTP_FROM=<your email address>
      - SMTP_FROM_NAME=VaultWarden
      - SMTP_SECURITY=starttls
      - SMTP_PORT=587
      - SMTP_USERNAME=<your google email login>
      - SMTP_PASSWORD=<custom generated app password>
      - SMTP_TIMEOUT=30
      - SMTP_AUTH_MECHANISM="Plain"
      - LOGIN_RATELIMIT_MAX_BURST=5
      - LOGIN_RATELIMIT_SECONDS=60
      - DOMAIN=https://<subdomain.domain>
      - INVITATION_ORG_NAME=VaultWarden
      - INVITATION_ALLOWED=true
      - ADMIN_TOKEN=<admin token password>
      - SIGNUPS_ALLOWED=false
      - SIGNUPS_DOMAINS_WHITELIST=<whitelisted domain that people can register with>
      - SIGNUPS_VERIFY=true
      - SIGNUPS_VERIFY_RESEND_TIME=3600
      - SIGNUPS_VERIFY_RESEND_LIMIT=2
      - EMERGENCY_ACCESS_ALLOWED=true
      - SENDS_ALLOWED=true
      - WEB_VAULT_ENABLED=true
