version: '2.1'

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr

    restart: unless-stopped

    ports:
      - 7878:7878

    volumes:
      - </path/to/host/config>:/config
      - </path/to/host/movies>:/movies
      - </path/to/host/Downloads>:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
