version: "3.7"
services:
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban_docker-pi
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - "</path/to/host/data>:/data"
      - "/var/log/auth.log:/var/log/auth.log:ro"
      - "</path/to/nginx-proxy-manager/data/logs/>:/log/npm/:ro"
    restart: always
    environment:
      - TZ=Europe/Europe
      - F2B_LOG_TARGET=STDOUT
      - F2B_LOG_LEVEL=INFO
      - F2B_DB_PURGE_AGE=1d
      - SSMTP_HOST=smtp.example.com
      - SSMTP_PORT=587
      - SSMTP_HOSTNAME=example.com
      - SSMTP_USER=smtp@example.com
      - SSMTP_PASSWORD=
      - SSMTP_TLS=YES
