version: '2.1'

services:
  snipeit:
    image: lscr.io/linuxserver/snipe-it:latest
    container_name: snipe-it

    restart: unless-stopped
    depends_on:
      - mysql

    ports:
      - <chosen port>:80

    volumes:
      - </path/to/host/config>:/config
    environment:
      - PUID=<$ id u>
      - PGID=<$ id g>
      - APP_ENV=production
      - APP_URL=http://<local ip-address>:<port>
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=<database name>
      - MYSQL_USER=<username>
      - MYSQL_PASSWORD=<password>
      - TZ=Europe/Brussels
      - MAIL_PORT_587_TCP_ADDR=smtp.gmail.com
      - MAIL_PORT_587_TCP_PORT=587
      - MAIL_ENV_USERNAME=<email>
      - MAIL_ENV_PASSWORD=<google app password>
      - MAIL_ENV_ENCRYPTION=tls
      - MAIL_ENV_FROM_ADDR=<email>
      - MAIL_ENV_FROM_NAME="<name>"

  mysql:
    image: mysql:5
    container_name: snipe_mysql

    restart: always

    volumes:
      - </path/to/host/data>:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<root password>
      - MYSQL_USER=<username>
      - MYSQL_PASSWORD=<password>
      - MYSQL_DATABASE=<database name>
